### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/dune-adapter#4]
We should add a license here. I would suggest LGPL-3.0. Main reason here is consistency with the other projects under the preCICE organization.

@maxfirmbach: We should to do this early, because changing the license becomes more complicated when more people contribute to the code. Currently, we are still quite lonely here.

**Comment by uekerman** [comment]
DUNE itself is GPL v2. Depending on how much DUNE data structures we use in the adapter, we might be bound to this one.
We handle the CalculiX and OpenFOAM adapters similarly.

**Comment by ajaust** [comment]
To be more precise: DUNE uses [GPLv2 with a runtime exception](https://dune-project.org/about/license/). DuMuX (as a DUNE module) [uses plain GPLv3](https://git.iws.uni-stuttgart.de/dumux-repositories/dumux/-/blob/master/LICENSE.md) explicitly mentioning the lack of runtime exception compared to DUNE.

To me this would be two choices that seem to be compatible with DUNE.
